Add support for Dual and Neutral classes on Duels stats
HearthSim/Hearthstone-Deck-Tracker pull request #4433
Opened 2022-09-20 23:31 UTC by edipo2s

- [ ] I have read the [Contributing Guidelines](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md#contributing)
- [ ] I have already signed the CLA

2022-09-23 16:33 UTC, azeier requested changes
Did you test what the interaction with the "default" decks is? When you play a game without an active deck selected it goes into the "DefaultDeckStats" system, which is essentially an unnamed deck for each class.

 My matchup table currently looks like this
![image](https://user-images.githubusercontent.com/7737910/192008210-197c2f24-2fa9-46b1-a3f2-d1150c447916.png)

With these two matches in them
![image](https://user-images.githubusercontent.com/7737910/192008316-028563ae-a77f-40ae-9b50-a56dd4f09da9.png)

```xml
    <DeckStats>
      <DeckId>00000000-0000-0000-0000-000000000000</DeckId>
      <Games>
        <Game>
          <GameId>3150d0fa-d687-4a10-ba97-0f75cdfbd935</GameId>
          <PlayerHero>Diablo</PlayerHero>
          <OpponentHero>Rattlegore</OpponentHero>
          <Coin>true</Coin>
          <GameMode>Duels</GameMode>
          <Result>Loss</Result>
          <Turns>0</Turns>
          <StartTime>2021-11-17T16:18:28.1163677-08:00</StartTime>
          <EndTime>2021-11-17T16:18:38.019061-08:00</EndTime>
          <PlayerName>Epix#2966</PlayerName>
          <OpponentName>Rattlegore</OpponentName>
          <ReplayFile>Epix#2966(Diablo) vs Rattlegore(Rattlegore) 1618-171121.hdtreplay</ReplayFile>
          <WasConceded>true</WasConceded>
          <HearthstoneBuild>60915</HearthstoneBuild>
          <OpponentCardbackId>250</OpponentCardbackId>
          <FriendlyPlayerId>2</FriendlyPlayerId>
          <OpponentPlayerId>1</OpponentPlayerId>
          <ScenarioId>4429</ScenarioId>
          <ServerInfo>
            <Address>37.244.49.185</Address>
            <AuroraPassword>DPflFK</AuroraPassword>
            <ClientHandle>192564</ClientHandle>
            <GameHandle>16108</GameHandle>
            <Mission>4429</Mission>
            <Port>3724</Port>
            <Resumable>true</Resumable>
            <SpectatorMode>false</SpectatorMode>
            <SpectatorPassword>FIBKHn</SpectatorPassword>
            <Version>2540310</Version>
          </ServerInfo>
          <GameType>GT_PVPDR</GameType>
          <RankedSeasonId>97</RankedSeasonId>
          <OpponentHeroCardId>PVPDR_Hero_Rattlegore</OpponentHeroCardId>
          <Region>EU</Region>
          <DeckId>00000000-0000-0000-0000-000000000000</DeckId>
          <DeckName>none</DeckName>
          <HsReplay>
            <UploadId>XCsX4hLVNMX3NBQg6P486E</UploadId>
            <UploadTries>1</UploadTries>
            <Unsupported>false</Unsupported>
            <ReplayUrl>https://hsreplay.net/uploads/upload/XCsX4hLVNMX3NBQg6P486E/</ReplayUrl>
          </HsReplay>
          <PlayerCards>
            <Card Id="EX1_316" Count="1" />
            <Card Id="UNG_829" Count="1" />
            <Card Id="CORE_OG_241" Count="1" />
            <Card Id="SCH_702" Count="1" />
          </PlayerCards>
        </Game>
      </Games>
      <Name>Diablo</Name>
    </DeckStats>
```
```xml
    <DeckStats>
      <DeckId>00000000-0000-0000-0000-000000000000</DeckId>
      <Games>
        <Game>
          <GameId>40f3317b-1663-46a1-847e-e94189ac90c7</GameId>
          <PlayerHero>Turalyon, the Tenured</PlayerHero>
          <OpponentHero>Mozaki, Master Duelist</OpponentHero>
          <Coin>true</Coin>
          <GameMode>Duels</GameMode>
          <Result>Loss</Result>
          <Turns>2</Turns>
          <StartTime>2021-11-17T17:35:43.7579059-08:00</StartTime>
          <EndTime>2021-11-17T17:37:05.130384-08:00</EndTime>
          <PlayerName>Epix#2966</PlayerName>
          <OpponentName>Mozaki, Master Duelist</OpponentName>
          <ReplayFile>Epix#2966(Turalyon, the Tenured) vs Mozaki, Master Duelist(Mozaki, Master Duelist) 1737-171121.hdtreplay</ReplayFile>
          <WasConceded>true</WasConceded>
          <HearthstoneBuild>60915</HearthstoneBuild>
          <PlayerCardbackId>139</PlayerCardbackId>
          <OpponentCardbackId>157</OpponentCardbackId>
          <FriendlyPlayerId>1</FriendlyPlayerId>
          <OpponentPlayerId>2</OpponentPlayerId>
          <ScenarioId>4429</ScenarioId>
          <ServerInfo>
            <Address>37.244.49.206</Address>
            <AuroraPassword>DMoNeI</AuroraPassword>
            <ClientHandle>192564</ClientHandle>
            <GameHandle>16079</GameHandle>
            <Mission>4429</Mission>
            <Port>3724</Port>
            <Resumable>true</Resumable>
            <SpectatorMode>false</SpectatorMode>
            <SpectatorPassword>AonEIH</SpectatorPassword>
            <Version>2540310</Version>
          </ServerInfo>
          <GameType>GT_PVPDR</GameType>
          <RankedSeasonId>97</RankedSeasonId>
          <OpponentHeroCardId>PVPDR_Hero_Mozaki</OpponentHeroCardId>
          <Region>EU</Region>
          <DeckId>0beea5e0-56df-492f-9af3-c073e9be6518</DeckId>
          <DeckName>Duels Run 17-11 17:35</DeckName>
          <PlayerDeckVersion>
            <Build>0</Build>
            <Major>1</Major>
            <Minor>0</Minor>
            <Revision>0</Revision>
          </PlayerDeckVersion>
          <HsReplay>
            <UploadId>DzUM63GJqAM8DgPa34coxE</UploadId>
            <UploadTries>1</UploadTries>
            <Unsupported>false</Unsupported>
            <ReplayUrl>https://hsreplay.net/uploads/upload/DzUM63GJqAM8DgPa34coxE/</ReplayUrl>
          </HsReplay>
          <PlayerCards>
            <Card Id="CS2_087" Count="1" />
            <Card Id="OG_223" Count="1" />
            <Card Id="BAR_550" Count="1" />
            <Card Id="EX1_132" Count="1" />
            <Card Id="CS2_091" Count="1" />
            <Card Id="SCH_247" Count="1" />
            <Card Id="EX1_371" Count="1" />
            <Card Id="CORE_FP1_020" Count="1" />
            <Card Id="OG_198" Count="1" Unconfirmed="1" />
            <Card Id="UNG_961" Count="1" Unconfirmed="1" />
            <Card Id="SW_049" Count="1" Unconfirmed="1" />
            <Card Id="EX1_363" Count="1" Unconfirmed="1" />
            <Card Id="EX1_360" Count="1" Unconfirmed="1" />
            <Card Id="BAR_873" Count="1" Unconfirmed="1" />
            <Card Id="UNG_960" Count="1" Unconfirmed="1" />
            <Card Id="PVPDR_YOP_PaladinT1" Count="1" Unconfirmed="1" />
          </PlayerCards>
          <OpponentCards>
            <Card Id="SW_450" Count="1" />
            <Card Id="BAR_546" Count="1" />
          </OpponentCards>
        </Game>      
      </Games>
      <Name>Paladin</Name>
    </DeckStats>
```

2022-09-23 16:33 UTC, azeier commented on Hearthstone Deck Tracker/Hearthstone/Card.cs
> +		public int MultipleClasses => _dbCard?.Entity.GetTag(GameTag.MULTIPLE_CLASSES) ?? 0;
This appears to be unused?

2022-09-23 16:33 UTC, azeier commented on Hearthstone Deck Tracker/GameEventHandler.cs
> +				var hero= Database.GetCardFromId(cardId);
Missing whitespace before the `=`

2022-09-23 16:33 UTC, azeier commented on Hearthstone Deck Tracker/GameEventHandler.cs
> +			if(heroName == null)
Is these a reason for this to not check `string.IsNullOrEmpty`?

2022-09-23 16:33 UTC, azeier commented on Hearthstone Deck Tracker/GameEventHandler.cs
> +			if(heroName == null)
Is these a reason for this to not check `string.IsNullOrEmpty`?

2022-09-23 16:43 UTC, azeier commented on Hearthstone Deck Tracker/Stats/GameStats.cs
> +		public string[]? OpponentHeroClasses { get; set; }
Add `ShouldSerialize` entries for these so we don't write a bunch of nulls to the game stats files. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/47d565774f7b03bf0482fa9a71b9d09695a96189/Hearthstone%20Deck%20Tracker/Stats/GameStats.cs#L563

2022-09-23 18:18 UTC, edipo2s commented on Hearthstone Deck Tracker/Enums/HeroClass.cs
> +		[LocDescription("Enum_HeroClass_Neutral")]
ah right, forgot to commit it

2022-09-23 19:30 UTC, edipo2s commented
> Did you test what the interaction with the "default" decks is? When you play a game without an active deck selected it goes into the "DefaultDeckStats" system, which is essentially an unnamed deck for each class.
> 
> My matchup table currently looks like this ![image](https://user-images.githubusercontent.com/7737910/192008210-197c2f24-2fa9-46b1-a3f2-d1150c447916.png)
> 
> With these two matches in them ![image](https://user-images.githubusercontent.com/7737910/192008316-028563ae-a77f-40ae-9b50-a56dd4f09da9.png)
> 
> ```
>     <DeckStats>
>       <DeckId>00000000-0000-0000-0000-000000000000</DeckId>
>       <Games>
>         <Game>
>           <GameId>3150d0fa-d687-4a10-ba97-0f75cdfbd935</GameId>
>           <PlayerHero>Diablo</PlayerHero>
>           <OpponentHero>Rattlegore</OpponentHero>
>           <Coin>true</Coin>
>           <GameMode>Duels</GameMode>
>           <Result>Loss</Result>
>           <Turns>0</Turns>
>           <StartTime>2021-11-17T16:18:28.1163677-08:00</StartTime>
>           <EndTime>2021-11-17T16:18:38.019061-08:00</EndTime>
>           <PlayerName>Epix#2966</PlayerName>
>           <OpponentName>Rattlegore</OpponentName>
>           <ReplayFile>Epix#2966(Diablo) vs Rattlegore(Rattlegore) 1618-171121.hdtreplay</ReplayFile>
>           <WasConceded>true</WasConceded>
>           <HearthstoneBuild>60915</HearthstoneBuild>
>           <OpponentCardbackId>250</OpponentCardbackId>
>           <FriendlyPlayerId>2</FriendlyPlayerId>
>           <OpponentPlayerId>1</OpponentPlayerId>
>           <ScenarioId>4429</ScenarioId>
>           <ServerInfo>
>             <Address>37.244.49.185</Address>
>             <AuroraPassword>DPflFK</AuroraPassword>
>             <ClientHandle>192564</ClientHandle>
>             <GameHandle>16108</GameHandle>
>             <Mission>4429</Mission>
>             <Port>3724</Port>
>             <Resumable>true</Resumable>
>             <SpectatorMode>false</SpectatorMode>
>             <SpectatorPassword>FIBKHn</SpectatorPassword>
>             <Version>2540310</Version>
>           </ServerInfo>
>           <GameType>GT_PVPDR</GameType>
>           <RankedSeasonId>97</RankedSeasonId>
>           <OpponentHeroCardId>PVPDR_Hero_Rattlegore</OpponentHeroCardId>
>           <Region>EU</Region>
>           <DeckId>00000000-0000-0000-0000-000000000000</DeckId>
>           <DeckName>none</DeckName>
>           <HsReplay>
>             <UploadId>XCsX4hLVNMX3NBQg6P486E</UploadId>
>             <UploadTries>1</UploadTries>
>             <Unsupported>false</Unsupported>
>             <ReplayUrl>https://hsreplay.net/uploads/upload/XCsX4hLVNMX3NBQg6P486E/</ReplayUrl>
>           </HsReplay>
>           <PlayerCards>
>             <Card Id="EX1_316" Count="1" />
>             <Card Id="UNG_829" Count="1" />
>             <Card Id="CORE_OG_241" Count="1" />
>             <Card Id="SCH_702" Count="1" />
>           </PlayerCards>
>         </Game>
>       </Games>
>       <Name>Diablo</Name>
>     </DeckStats>
> ```
> 
> ```
>     <DeckStats>
>       <DeckId>00000000-0000-0000-0000-000000000000</DeckId>
>       <Games>
>         <Game>
>           <GameId>40f3317b-1663-46a1-847e-e94189ac90c7</GameId>
>           <PlayerHero>Turalyon, the Tenured</PlayerHero>
>           <OpponentHero>Mozaki, Master Duelist</OpponentHero>
>           <Coin>true</Coin>
>           <GameMode>Duels</GameMode>
>           <Result>Loss</Result>
>           <Turns>2</Turns>
>           <StartTime>2021-11-17T17:35:43.7579059-08:00</StartTime>
>           <EndTime>2021-11-17T17:37:05.130384-08:00</EndTime>
>           <PlayerName>Epix#2966</PlayerName>
>           <OpponentName>Mozaki, Master Duelist</OpponentName>
>           <ReplayFile>Epix#2966(Turalyon, the Tenured) vs Mozaki, Master Duelist(Mozaki, Master Duelist) 1737-171121.hdtreplay</ReplayFile>
>           <WasConceded>true</WasConceded>
>           <HearthstoneBuild>60915</HearthstoneBuild>
>           <PlayerCardbackId>139</PlayerCardbackId>
>           <OpponentCardbackId>157</OpponentCardbackId>
>           <FriendlyPlayerId>1</FriendlyPlayerId>
>           <OpponentPlayerId>2</OpponentPlayerId>
>           <ScenarioId>4429</ScenarioId>
>           <ServerInfo>
>             <Address>37.244.49.206</Address>
>             <AuroraPassword>DMoNeI</AuroraPassword>
>             <ClientHandle>192564</ClientHandle>
>             <GameHandle>16079</GameHandle>
>             <Mission>4429</Mission>
>             <Port>3724</Port>
>             <Resumable>true</Resumable>
>             <SpectatorMode>false</SpectatorMode>
>             <SpectatorPassword>AonEIH</SpectatorPassword>
>             <Version>2540310</Version>
>           </ServerInfo>
>           <GameType>GT_PVPDR</GameType>
>           <RankedSeasonId>97</RankedSeasonId>
>           <OpponentHeroCardId>PVPDR_Hero_Mozaki</OpponentHeroCardId>
>           <Region>EU</Region>
>           <DeckId>0beea5e0-56df-492f-9af3-c073e9be6518</DeckId>
>           <DeckName>Duels Run 17-11 17:35</DeckName>
>           <PlayerDeckVersion>
>             <Build>0</Build>
>             <Major>1</Major>
>             <Minor>0</Minor>
>             <Revision>0</Revision>
>           </PlayerDeckVersion>
>           <HsReplay>
>             <UploadId>DzUM63GJqAM8DgPa34coxE</UploadId>
>             <UploadTries>1</UploadTries>
>             <Unsupported>false</Unsupported>
>             <ReplayUrl>https://hsreplay.net/uploads/upload/DzUM63GJqAM8DgPa34coxE/</ReplayUrl>
>           </HsReplay>
>           <PlayerCards>
>             <Card Id="CS2_087" Count="1" />
>             <Card Id="OG_223" Count="1" />
>             <Card Id="BAR_550" Count="1" />
>             <Card Id="EX1_132" Count="1" />
>             <Card Id="CS2_091" Count="1" />
>             <Card Id="SCH_247" Count="1" />
>             <Card Id="EX1_371" Count="1" />
>             <Card Id="CORE_FP1_020" Count="1" />
>             <Card Id="OG_198" Count="1" Unconfirmed="1" />
>             <Card Id="UNG_961" Count="1" Unconfirmed="1" />
>             <Card Id="SW_049" Count="1" Unconfirmed="1" />
>             <Card Id="EX1_363" Count="1" Unconfirmed="1" />
>             <Card Id="EX1_360" Count="1" Unconfirmed="1" />
>             <Card Id="BAR_873" Count="1" Unconfirmed="1" />
>             <Card Id="UNG_960" Count="1" Unconfirmed="1" />
>             <Card Id="PVPDR_YOP_PaladinT1" Count="1" Unconfirmed="1" />
>           </PlayerCards>
>           <OpponentCards>
>             <Card Id="SW_450" Count="1" />
>             <Card Id="BAR_546" Count="1" />
>           </OpponentCards>
>         </Game>      
>       </Games>
>       <Name>Paladin</Name>
>     </DeckStats>
> ```

Stats for those default decks are working. What happens in your table was that you had a game with an old hero (Diablo) that was not in the hero classes mapping. I looked for old removed heroes but did not find any other, so I just add the Diablo that was missing there.

2022-09-23 20:04 UTC, anonymous555 commented
Does this support duels deck import too?

2022-09-27 15:58 UTC, edipo2s commented
> Does this support duels deck import too?

Sorry, no. This is about add support for the Duels in the constructed matchups table

2022-09-27 16:03 UTC, merged